// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorWebApp.Data;

#nullable disable

namespace RazorWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazerWebApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayOrder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = "1",
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = "2",
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = "3",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = "4",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = "5",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = "6",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = "7",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = "8",
                            Name = "Westerns"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = "9",
                            Name = "Dystopian"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = "10",
                            Name = "Contemporary"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
