// <auto-generated />
using DotnetWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230808213037_seedCategoryTable")]
    partial class seedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotnetWebApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayOrder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = "1",
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = "2",
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = "3",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = "4",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = "5",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = "6",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = "7",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = "8",
                            Name = "Westerns"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = "9",
                            Name = "Dystopian"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = "10",
                            Name = "Contemporary"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = "11",
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = "12",
                            Name = "History"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = "13",
                            Name = "Biographies"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = "14",
                            Name = "Autobiographies"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = "15",
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = "16",
                            Name = "Cookbooks"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = "17",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = "18",
                            Name = "Religion, Spirituality & New Age"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = "19",
                            Name = "Science"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = "20",
                            Name = "Math"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = "21",
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = "22",
                            Name = "Encyclopedias"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = "23",
                            Name = "Dictionaries"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = "24",
                            Name = "Comics"
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = "25",
                            Name = "Art"
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = "26",
                            Name = "Journals"
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = "27",
                            Name = "Series"
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = "28",
                            Name = "Trilogy"
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = "29",
                            Name = "Bi-monthly"
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = "30",
                            Name = "Monthly"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
